import img1 from '../images/EN_RLT_AnimeGirl_1200x627.jpg'
import img2 from '../images/EN_RLT_3DKissNoText_1200x627.jpg'

const campaigns = [
  {
    campaignId: 1548,
    campaignName:
      'Casino Roulette: Roulettist / Android / US / CPE / New funnel',
    capReached: false,
    rankingScore: 156.36,
    campaignDescription:
      '1. Play and enjoy Casino Roulette: Roulettist!\n2. Complete the tasks listed to collect your points!\n3. Each task has a time limit! Complete the event on time to be able to collect the points!\n4. You must be a new player to get rewarded',
    offerId: '22572',
    status: 'paused',
    reportingCampaignName:
      'TyrAds - Roulette And - US - CPE - 90 level - Multilevel - NonLinear - 26.01.2024',
    app: {
      id: 396,
      title: 'Casino Roulette: Roulettist',
      packageName: 'com.kamagames.roulettist',
      rating: 4.43596,
      shortDescription:
        'An all-new, free roulette game with stunning, realistic 3D graphics',
      store: 'googlePlay',
      storeCategory: 'Casino',
      previewUrl:
        'https://play.google.com/store/apps/details?id=com.kamagames.roulettist',
      thumbnail:
        'https://play-lh.googleusercontent.com/zEGBm8IOMlxOoUSzVVWwr6NHgFK7gzL3vsg4arGYHp-S2-_UYSHkHg7ajF9LY52-Gto',
    },
    currency: {
      name: 'USD',
      symbol: '$',
    },
    kpis: [
      {
        id: 2179,
        kpiType: 'Soft',
        eventType: 'ROI',
        eventName: '',
        rules: [
          {
            rule: 'More Than',
            goal: '10',
            unit: '%',
            criteriaFirst: '',
            criteriaSecond: '',
            payout: '',
          },
        ],
        appEventId: null,
        appEventIdentifier: null,
      },
      {
        id: 2180,
        kpiType: 'Soft',
        eventType: 'ROI',
        eventName: '',
        rules: [
          {
            rule: 'More Than',
            goal: '20',
            unit: '%',
            criteriaFirst: '',
            criteriaSecond: '',
            payout: '',
          },
        ],
        appEventId: null,
        appEventIdentifier: null,
      },
    ],
    payoutEvents: [
      {
        id: 313286,
        identifier: 'Install',
        eventName: 'Install',
        eventDescription: null,
        eventCategory: null,
        payoutAmount: 0,
        payoutTypeId: 1,
        payoutType: 'CPI',
        allowDuplicateEvents: false,
        maxTime: null,
        maxTimeMetric: null,
        enforceEventOrder: false,
        enforceMaxTimeCompletion: false,
        everflowEventId: 36325,
        appEventId: 716,
        userPayout: null,
      },
      {
        id: 313287,
        identifier: '15level',
        eventName: 'Complete level 15',
        eventDescription: '1 day',
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 2.27,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 3,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36333,
        appEventId: 715,
        userPayout: null,
      },
      {
        id: 313288,
        identifier: '30level',
        eventName: 'Complete level 30',
        eventDescription: '1-3 days',
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 6.5,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 5,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36334,
        appEventId: 714,
        userPayout: null,
      },
      {
        id: 313289,
        identifier: '50level',
        eventName: 'Complete level 50',
        eventDescription: '3-5 days',
        eventCategory: 'Level achieved - Medium',
        payoutAmount: 29.25,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 20,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36335,
        appEventId: 713,
        userPayout: null,
      },
      {
        id: 313290,
        identifier: '70level',
        eventName: 'Complete level 70',
        eventDescription: '5+ days',
        eventCategory: 'Level achieved - High',
        payoutAmount: 65,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36336,
        appEventId: 712,
        userPayout: null,
      },
      {
        id: 313291,
        identifier: '90level',
        eventName: 'Complete level 90',
        eventDescription: '7 + days',
        eventCategory: 'Level achieved - High',
        payoutAmount: 162.5,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36326,
        appEventId: 711,
        userPayout: null,
      },
      {
        id: 313292,
        identifier: 'spinner_20',
        eventName:
          'Spin the slots in the app 20 times and claim your reward!\t',
        eventDescription: null,
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 0.2,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36337,
        appEventId: 3801,
        userPayout: null,
      },
      {
        id: 313293,
        identifier: 'achievement_1',
        eventName:
          "Get rewarded by playing poker 15 times – it's that simple!\t",
        eventDescription: null,
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 0.3,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36330,
        appEventId: 3802,
        userPayout: null,
      },
      {
        id: 313294,
        identifier: 'vp10',
        eventName: 'Do 10 spins in the exciting Video Poker game!\t',
        eventDescription: null,
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 0.2,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36329,
        appEventId: 3804,
        userPayout: null,
      },
      {
        id: 313295,
        identifier: 'Spin_1',
        eventName:
          'Unlock a reward by giving roulette a try, even just once!\t',
        eventDescription: null,
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 0.2,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36338,
        appEventId: 3803,
        userPayout: null,
      },
      {
        id: 313296,
        identifier: 'hand_2',
        eventName:
          'Get rewarded for your Blackjack prowess – win 5 times and claim your prize!',
        eventDescription: null,
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 0.2,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36331,
        appEventId: 3805,
        userPayout: null,
      },
      {
        id: 313297,
        identifier: 'placed_bets_5',
        eventName: 'Place 5 bets and get rewards',
        eventDescription: null,
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 0.65,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36332,
        appEventId: 3806,
        userPayout: null,
      },
      {
        id: 313298,
        identifier: 'cp_free_rewards_collected',
        eventName:
          'Complete your collection of free rewards in the Casino Pass and get rewarded\t',
        eventDescription: null,
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 0.65,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36327,
        appEventId: 3807,
        userPayout: null,
      },
      {
        id: 313299,
        identifier: 'cp_elite_rewards_collected',
        eventName:
          'Complete your elite reward collection in the Casino Pass and enjoy a special prize!',
        eventDescription: null,
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 4.23,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36328,
        appEventId: 3808,
        userPayout: null,
      },
      {
        id: 313303,
        identifier: 'af_purchase',
        eventName: 'Make a Purchase',
        eventDescription: null,
        eventCategory: 'Purchase',
        payoutAmount: 0,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: true,
        maxTime: 0,
        maxTimeMetric: null,
        enforceEventOrder: false,
        enforceMaxTimeCompletion: false,
        everflowEventId: 50151,
        appEventId: 8094,
        userPayout: null,
      },
    ],
    publisherBudgets: [
      {
        id: 47843,
        budgetType: {
          id: 3,
          name: 'Click Caps',
        },
        dailyBudget: null,
        weeklyBudget: null,
        monthlyBudget: null,
        globalBudget: null,
        isActive: true,
      },
      {
        id: 47844,
        budgetType: {
          id: 4,
          name: 'Conversion Caps',
        },
        dailyBudget: null,
        weeklyBudget: null,
        monthlyBudget: null,
        globalBudget: null,
        isActive: true,
      },
      {
        id: 47845,
        budgetType: {
          id: 5,
          name: 'Revenue Caps',
        },
        dailyBudget: null,
        weeklyBudget: null,
        monthlyBudget: null,
        globalBudget: null,
        isActive: true,
      },
    ],
    tracking: {
      id: 3104,
      attributionTool: 'Appsflyer',
      clickUrl: 'https://www.ltv-mob.com/KMHQ5J/2DZGKP9F/',
      impressionUrl: 'https://www.ltv-mob.com/i/KMHQ5J/2DZGKP9F/',
    },
    targeting: {
      os: 'Android',
      countries: [
        {
          id: 226,
          iso: 'US',
        },
      ],
      demographics: [],
      targetingType: 'incent',
      reward: null,
    },
    creative: {
      creativeUrl: '.',
      creativePacks: [
        {
          creativePackName: 'rt1',
          languageName: 'English',
          languageCode: 'en',
          creatives: [
            {
              creativeName: 'rt1_en_RewardedBanner_1200x627',
              callToAction: null,
              text: '',
              byteSize: '165845',
              fileUrl: img1,
              duration: null,
              creativeType: {
                name: 'Rewarded Banner',
                type: 'image',
                width: '1200',
                height: '627',
                creativeCategoryType: 'Rewarded Play',
              },
            },
            {
              creativeName: 'rt1_en_RewardedBanner_1200x627',
              callToAction: null,
              text: '',
              byteSize: '157045',
              fileUrl: img2,
              duration: null,
              creativeType: {
                name: 'Rewarded Banner',
                type: 'image',
                width: '1200',
                height: '627',
                creativeCategoryType: 'Rewarded Play',
              },
            },
            {
              creativeName: 'rt1_native_text',
              callToAction: null,
              text: '',
              byteSize: '0',
              fileUrl: '',
              duration: null,
              creativeType: {
                name: 'Rewarded Text',
                type: 'text',
                width: null,
                height: null,
                creativeCategoryType: 'Rewarded Play',
              },
            },
          ],
        },
      ],
    },
  },
]

export default campaigns
