import img1 from '../../images/EN_RLT_AnimeGirl_1200x627.jpg'
import img2 from '../../images/EN_RLT_3DKissNoText_1200x627.jpg'

const campaigns = [
  {
    campaignId: 1548,
    campaignName:
      'Casino Roulette: Roulettist / Android / US / CPE / New funnel',
    capReached: false,
    rankingScore: 156.36,
    campaignDescription:
      '1. Play and enjoy Casino Roulette: Roulettist!\n2. Complete the tasks listed to collect your points!\n3. Each task has a time limit! Complete the event on time to be able to collect the points!\n4. You must be a new player to get rewarded',
    offerId: '22572',
    status: 'paused',
    reportingCampaignName:
      'TyrAds - Roulette And - US - CPE - 90 level - Multilevel - NonLinear - 26.01.2024',
    app: {
      id: 396,
      title: 'Casino Roulette: Roulettist',
      packageName: 'com.kamagames.roulettist',
      rating: 4.43596,
      shortDescription:
        'An all-new, free roulette game with stunning, realistic 3D graphics',
      store: 'googlePlay',
      storeCategory: 'Casino',
      previewUrl:
        'https://play.google.com/store/apps/details?id=com.kamagames.roulettist',
      thumbnail:
        'https://play-lh.googleusercontent.com/zEGBm8IOMlxOoUSzVVWwr6NHgFK7gzL3vsg4arGYHp-S2-_UYSHkHg7ajF9LY52-Gto',
    },
    currency: {
      name: 'USD',
      symbol: '$',
    },
    kpis: [
      {
        id: 2179,
        kpiType: 'Soft',
        eventType: 'ROI',
        eventName: '',
        rules: [
          {
            rule: 'More Than',
            goal: '10',
            unit: '%',
            criteriaFirst: '',
            criteriaSecond: '',
            payout: '',
          },
        ],
        appEventId: null,
        appEventIdentifier: null,
      },
      {
        id: 2180,
        kpiType: 'Soft',
        eventType: 'ROI',
        eventName: '',
        rules: [
          {
            rule: 'More Than',
            goal: '20',
            unit: '%',
            criteriaFirst: '',
            criteriaSecond: '',
            payout: '',
          },
        ],
        appEventId: null,
        appEventIdentifier: null,
      },
    ],
    payoutEvents: [
      {
        id: 313286,
        identifier: 'Install',
        eventName: 'Install',
        eventDescription: null,
        eventCategory: null,
        payoutAmount: 0,
        payoutTypeId: 1,
        payoutType: 'CPI',
        allowDuplicateEvents: false,
        maxTime: null,
        maxTimeMetric: null,
        enforceEventOrder: false,
        enforceMaxTimeCompletion: false,
        everflowEventId: 36325,
        appEventId: 716,
        userPayout: null,
      },
      {
        id: 313287,
        identifier: '15level',
        eventName: 'Complete level 15',
        eventDescription: '1 day',
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 2.27,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 3,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36333,
        appEventId: 715,
        userPayout: null,
      },
      {
        id: 313288,
        identifier: '30level',
        eventName: 'Complete level 30',
        eventDescription: '1-3 days',
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 6.5,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 5,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36334,
        appEventId: 714,
        userPayout: null,
      },
      {
        id: 313289,
        identifier: '50level',
        eventName: 'Complete level 50',
        eventDescription: '3-5 days',
        eventCategory: 'Level achieved - Medium',
        payoutAmount: 29.25,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 20,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36335,
        appEventId: 713,
        userPayout: null,
      },
      {
        id: 313290,
        identifier: '70level',
        eventName: 'Complete level 70',
        eventDescription: '5+ days',
        eventCategory: 'Level achieved - High',
        payoutAmount: 65,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36336,
        appEventId: 712,
        userPayout: null,
      },
      {
        id: 313291,
        identifier: '90level',
        eventName: 'Complete level 90',
        eventDescription: '7 + days',
        eventCategory: 'Level achieved - High',
        payoutAmount: 162.5,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36326,
        appEventId: 711,
        userPayout: null,
      },
      {
        id: 313292,
        identifier: 'spinner_20',
        eventName:
          'Spin the slots in the app 20 times and claim your reward!\t',
        eventDescription: null,
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 0.2,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36337,
        appEventId: 3801,
        userPayout: null,
      },
      {
        id: 313293,
        identifier: 'achievement_1',
        eventName:
          "Get rewarded by playing poker 15 times – it's that simple!\t",
        eventDescription: null,
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 0.3,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36330,
        appEventId: 3802,
        userPayout: null,
      },
      {
        id: 313294,
        identifier: 'vp10',
        eventName: 'Do 10 spins in the exciting Video Poker game!\t',
        eventDescription: null,
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 0.2,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36329,
        appEventId: 3804,
        userPayout: null,
      },
      {
        id: 313295,
        identifier: 'Spin_1',
        eventName:
          'Unlock a reward by giving roulette a try, even just once!\t',
        eventDescription: null,
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 0.2,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36338,
        appEventId: 3803,
        userPayout: null,
      },
      {
        id: 313296,
        identifier: 'hand_2',
        eventName:
          'Get rewarded for your Blackjack prowess – win 5 times and claim your prize!',
        eventDescription: null,
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 0.2,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36331,
        appEventId: 3805,
        userPayout: null,
      },
      {
        id: 313297,
        identifier: 'placed_bets_5',
        eventName: 'Place 5 bets and get rewards',
        eventDescription: null,
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 0.65,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36332,
        appEventId: 3806,
        userPayout: null,
      },
      {
        id: 313298,
        identifier: 'cp_free_rewards_collected',
        eventName:
          'Complete your collection of free rewards in the Casino Pass and get rewarded\t',
        eventDescription: null,
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 0.65,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36327,
        appEventId: 3807,
        userPayout: null,
      },
      {
        id: 313299,
        identifier: 'cp_elite_rewards_collected',
        eventName:
          'Complete your elite reward collection in the Casino Pass and enjoy a special prize!',
        eventDescription: null,
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 4.23,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 36328,
        appEventId: 3808,
        userPayout: null,
      },
      {
        id: 313303,
        identifier: 'af_purchase',
        eventName: 'Make a Purchase',
        eventDescription: null,
        eventCategory: 'Purchase',
        payoutAmount: 0,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: true,
        maxTime: 0,
        maxTimeMetric: null,
        enforceEventOrder: false,
        enforceMaxTimeCompletion: false,
        everflowEventId: 50151,
        appEventId: 8094,
        userPayout: null,
      },
    ],
    publisherBudgets: [
      {
        id: 47843,
        budgetType: {
          id: 3,
          name: 'Click Caps',
        },
        dailyBudget: null,
        weeklyBudget: null,
        monthlyBudget: null,
        globalBudget: null,
        isActive: true,
      },
      {
        id: 47844,
        budgetType: {
          id: 4,
          name: 'Conversion Caps',
        },
        dailyBudget: null,
        weeklyBudget: null,
        monthlyBudget: null,
        globalBudget: null,
        isActive: true,
      },
      {
        id: 47845,
        budgetType: {
          id: 5,
          name: 'Revenue Caps',
        },
        dailyBudget: null,
        weeklyBudget: null,
        monthlyBudget: null,
        globalBudget: null,
        isActive: true,
      },
    ],
    tracking: {
      id: 3104,
      attributionTool: 'Appsflyer',
      clickUrl: 'https://www.ltv-mob.com/KMHQ5J/2DZGKP9F/',
      impressionUrl: 'https://www.ltv-mob.com/i/KMHQ5J/2DZGKP9F/',
    },
    targeting: {
      os: 'Android',
      countries: [
        {
          id: 226,
          iso: 'US',
        },
      ],
      demographics: [],
      targetingType: 'incent',
      reward: null,
    },
    creative: {
      creativeUrl: '.',
      creativePacks: [
        {
          creativePackName: 'rt1',
          languageName: 'English',
          languageCode: 'en',
          creatives: [
            {
              creativeName: 'rt1_en_RewardedBanner_1200x627',
              callToAction: null,
              text: '',
              byteSize: '165845',
              fileUrl: img1,
              duration: null,
              creativeType: {
                name: 'Rewarded Banner',
                type: 'image',
                width: '1200',
                height: '627',
                creativeCategoryType: 'Rewarded Play',
              },
            },
            {
              creativeName: 'rt1_en_RewardedBanner_1200x627',
              callToAction: null,
              text: '',
              byteSize: '157045',
              fileUrl: img2,
              duration: null,
              creativeType: {
                name: 'Rewarded Banner',
                type: 'image',
                width: '1200',
                height: '627',
                creativeCategoryType: 'Rewarded Play',
              },
            },
            {
              creativeName: 'rt1_native_text',
              callToAction: null,
              text: '',
              byteSize: '0',
              fileUrl: '',
              duration: null,
              creativeType: {
                name: 'Rewarded Text',
                type: 'text',
                width: null,
                height: null,
                creativeCategoryType: 'Rewarded Play',
              },
            },
          ],
        },
      ],
    },
  },
  {
    campaignId: 1363,
    campaignName:
      'Vegas Casino & Slots: Slottist / Android / US / Incent / NonLinear / NEW',
    capReached: false,
    rankingScore: 82.87,
    campaignDescription:
      '1. Play and enjoy Vegas Casino & Slots: Slottist!\n2. Complete the tasks listed to collect your points!\n3. Each task has a time limit! Complete the event on time to be able to collect the points!\n4. You must be a new player to get rewarded',
    offerId: '22368',
    status: 'paused',
    reportingCampaignName:
      'TyrAds - Slottist And - US - CPE - 90 level - Multilevel - NonLinear - 19.12.2023',
    app: {
      id: 353,
      title: 'Vegas Casino & Slots: Slottist',
      packageName: 'com.kamagames.slotist',
      rating: 4.50543,
      shortDescription:
        '#1 casino game! Play at our casino! Join your friends and millions of others!',
      store: 'googlePlay',
      storeCategory: 'Casino',
      previewUrl:
        'https://play.google.com/store/apps/details?id=com.kamagames.slotist',
      thumbnail:
        'https://play-lh.googleusercontent.com/h_GDqiuwF2apo7UIFtBS3JYT4MUChUNfefkTOeQXHibci2BM6VizAudqlaLChORflLg',
    },
    currency: {
      name: 'USD',
      symbol: '$',
    },
    kpis: [
      {
        id: 1945,
        kpiType: 'Soft',
        eventType: 'ROI',
        eventName: '',
        rules: [
          {
            rule: 'More Than',
            goal: '10',
            unit: '%',
            criteriaFirst: '',
            criteriaSecond: '',
            payout: '',
          },
        ],
        appEventId: null,
        appEventIdentifier: null,
      },
      {
        id: 1946,
        kpiType: 'Soft',
        eventType: 'ROI',
        eventName: '',
        rules: [
          {
            rule: 'More Than',
            goal: '20',
            unit: '%',
            criteriaFirst: '',
            criteriaSecond: '',
            payout: '',
          },
        ],
        appEventId: null,
        appEventIdentifier: null,
      },
    ],
    payoutEvents: [
      {
        id: 313507,
        identifier: 'Install',
        eventName: 'Install',
        eventDescription: null,
        eventCategory: null,
        payoutAmount: 0,
        payoutTypeId: 1,
        payoutType: 'CPI',
        allowDuplicateEvents: false,
        maxTime: null,
        maxTimeMetric: null,
        enforceEventOrder: false,
        enforceMaxTimeCompletion: false,
        everflowEventId: 34224,
        appEventId: 478,
        userPayout: null,
      },
      {
        id: 313508,
        identifier: '15level',
        eventName: 'Complete level 15',
        eventDescription: '1 day',
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 2.27,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 2,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 34225,
        appEventId: 477,
        userPayout: null,
      },
      {
        id: 313509,
        identifier: '30level',
        eventName: 'Complete level 30',
        eventDescription: '1-3 days',
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 6.5,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 5,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 34226,
        appEventId: 476,
        userPayout: null,
      },
      {
        id: 313510,
        identifier: '50level',
        eventName: 'Complete level 50',
        eventDescription: '3-5 days',
        eventCategory: 'Level achieved - Medium',
        payoutAmount: 29.25,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 14,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 34227,
        appEventId: 475,
        userPayout: null,
      },
      {
        id: 313511,
        identifier: '70level',
        eventName: 'Complete level 70',
        eventDescription: '5+ days',
        eventCategory: 'Level achieved - High',
        payoutAmount: 65,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 34228,
        appEventId: 474,
        userPayout: null,
      },
      {
        id: 313512,
        identifier: '90level',
        eventName: 'Complete level 90',
        eventDescription: '7 + days',
        eventCategory: 'Level achieved - High',
        payoutAmount: 162.5,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 34229,
        appEventId: 473,
        userPayout: null,
      },
      {
        id: 313513,
        identifier: 'spinner_20',
        eventName: 'Spin the slots in the app 20 times and claim your reward!',
        eventDescription: null,
        eventCategory: 'Unlocked achievement',
        payoutAmount: 0.07,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 34230,
        appEventId: 3148,
        userPayout: null,
      },
      {
        id: 313514,
        identifier: 'achievement_1',
        eventName: "Get rewarded by playing poker 15 times – it's that simple!",
        eventDescription: null,
        eventCategory: 'Unlocked achievement',
        payoutAmount: 0.65,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 34231,
        appEventId: 3149,
        userPayout: null,
      },
      {
        id: 313515,
        identifier: 'Spin_1',
        eventName: 'Unlock a reward by giving roulette a try, even just once!',
        eventDescription: null,
        eventCategory: 'Unlocked achievement',
        payoutAmount: 0.65,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 34232,
        appEventId: 3150,
        userPayout: null,
      },
      {
        id: 313521,
        identifier: 'vp10',
        eventName: 'Do 10 spins in the exciting Video Poker game!',
        eventDescription: null,
        eventCategory: 'Unlocked achievement',
        payoutAmount: 0.65,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 34233,
        appEventId: 3151,
        userPayout: null,
      },
      {
        id: 313516,
        identifier: 'hand_2',
        eventName:
          'Get rewarded for your Blackjack prowess – win 5 times and claim your prize!',
        eventDescription: null,
        eventCategory: 'Unlocked achievement',
        payoutAmount: 0.65,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 34234,
        appEventId: 3152,
        userPayout: null,
      },
      {
        id: 313517,
        identifier: 'placed_bets_5',
        eventName: 'Place 5 bets and get rewards',
        eventDescription: null,
        eventCategory: 'Unlocked achievement',
        payoutAmount: 0.65,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 34235,
        appEventId: 3153,
        userPayout: null,
      },
      {
        id: 313518,
        identifier: 'cp_free_rewards_collected',
        eventName:
          'Complete your collection of free rewards in the Casino Pass and get rewarded',
        eventDescription: null,
        eventCategory: 'Unlocked achievement',
        payoutAmount: 0.65,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 34236,
        appEventId: 3154,
        userPayout: null,
      },
      {
        id: 313519,
        identifier: 'cp_elite_rewards_collected',
        eventName:
          'Complete your elite reward collection in the Casino Pass and enjoy a special prize!',
        eventDescription: null,
        eventCategory: 'Unlocked achievement',
        payoutAmount: 1.95,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: true,
        everflowEventId: 34237,
        appEventId: 3155,
        userPayout: null,
      },
      {
        id: 313520,
        identifier: 'af_purchase',
        eventName: 'Make a Purchase',
        eventDescription: null,
        eventCategory: 'Purchase',
        payoutAmount: 0,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: true,
        maxTime: 0,
        maxTimeMetric: null,
        enforceEventOrder: false,
        enforceMaxTimeCompletion: false,
        everflowEventId: 43990,
        appEventId: 5627,
        userPayout: null,
      },
    ],
    publisherBudgets: [
      {
        id: 47911,
        budgetType: {
          id: 3,
          name: 'Click Caps',
        },
        dailyBudget: null,
        weeklyBudget: null,
        monthlyBudget: null,
        globalBudget: null,
        isActive: true,
      },
      {
        id: 47912,
        budgetType: {
          id: 4,
          name: 'Conversion Caps',
        },
        dailyBudget: null,
        weeklyBudget: null,
        monthlyBudget: null,
        globalBudget: null,
        isActive: true,
      },
      {
        id: 47913,
        budgetType: {
          id: 5,
          name: 'Revenue Caps',
        },
        dailyBudget: null,
        weeklyBudget: null,
        monthlyBudget: null,
        globalBudget: null,
        isActive: true,
      },
    ],
    tracking: {
      id: 2919,
      attributionTool: 'Appsflyer',
      clickUrl: 'https://www.ltv-mob.com/KMHQ5J/2DLC9H5K/',
      impressionUrl: 'https://www.ltv-mob.com/i/KMHQ5J/2DLC9H5K/',
    },
    targeting: {
      os: 'Android',
      countries: [
        {
          id: 226,
          iso: 'US',
        },
      ],
      demographics: [],
      targetingType: 'incent',
      reward: {
        rewardDifficulty: 'Easy',
        incentRewardDescription:
          "1. Play and enjoy {game_name}. \n2. Complete the tasks listed to collect your points! \n3. Each task has a time limit! Complete the event on time to be able to collect the points! \n4. You must be a new player to get rewarded.\n\n- Complete level 15 - Complete within 2 days\n- Complete level 30 - Complete within 5 days\n- Complete level 50 - Complete within 14 days\n- Complete level 70 - Complete within 30 days\n- Complete level 90 - Complete within 30 days\n- Spin the slots in the app 20 times and claim your reward! - Complete within 30 days\n- Get rewarded by playing poker 15 times – it's that simple! - Complete within 30 days\n- Unlock a reward by giving roulette a try, even just once! - Complete within 30 days\n- Get rewarded for your Blackjack prowess – win 5 times and claim your prize! - Complete within 30 days\n- Place 5 bets and get rewards - Complete within 30 days\n- Complete your collection of free rewards in the Casino Pass and get rewarded - Complete within 30 days\n- Complete your elite reward collection in the Casino Pass and enjoy a special prize! - Complete within 30 days\n- Do 10 spins in the exciting Video Poker game! - Complete within 30 days",
      },
    },
    creative: {
      creativeUrl:
        'https://drive.google.com/drive/folders/16xR8RKlRcYkPhCtCio_4KN5EEhAr7-zM?usp=sharing',
      creativePacks: [
        {
          creativePackName: 'Vegas Casino & Slots: Slottist',
          languageName: 'English',
          languageCode: 'en',
          creatives: [
            {
              creativeName:
                'Vegas_Casino_&_Slots:_Slottist_rewardedBanner_1200x627',
              callToAction: '',
              text: '',
              byteSize: '989871',
              fileUrl:
                'https://d1qzgjkat5an4y.cloudfront.net/353/1728566022509.png',
              duration: null,
              creativeType: {
                name: 'Rewarded Banner',
                type: 'image',
                width: '1200',
                height: '627',
                creativeCategoryType: 'Rewarded Play',
              },
            },
          ],
        },
      ],
    },
  },
  {
    campaignId: 696,
    campaignName: 'The Ants: Underground Kingdom / Android / US / Incent',
    capReached: false,
    rankingScore: 47.39,
    campaignDescription:
      '1. Play and enjoy The Ants: Underground Kingdom!\n2. Complete the tasks listed to collect your points!\n3. Each task has a time limit! Complete the event on time to be able to collect the points!\n4. You must be a new player to get rewarded',
    offerId: '21404',
    status: 'paused',
    reportingCampaignName: 'Tyrads_AN_US_AND_MRCPE_20230601',
    app: {
      id: 299,
      title: 'The Ants: Underground Kingdom',
      packageName: 'com.star.union.planetant',
      rating: 4.5814,
      shortDescription: 'Welcome to The Ants World',
      store: 'googlePlay',
      storeCategory: 'Strategy',
      previewUrl:
        'https://play.google.com/store/apps/details?id=com.star.union.planetant',
      thumbnail:
        'https://play-lh.googleusercontent.com/l_2_oHMP83nGDYBNMTK-7qXGHF8iiYbo9C-kODesK5r4PmlIqKRruqQtlUgyg7DVVpev=s180',
    },
    currency: {
      name: 'USD',
      symbol: '$',
    },
    kpis: [
      {
        id: 3235,
        kpiType: 'Soft',
        eventType: 'ROI',
        eventName: '',
        rules: [
          {
            rule: 'More Than',
            goal: '15',
            unit: '%',
            criteriaFirst: '',
            criteriaSecond: '',
            payout: '',
          },
        ],
        appEventId: null,
        appEventIdentifier: null,
      },
    ],
    payoutEvents: [
      {
        id: 312996,
        identifier: 'Install',
        eventName: 'Install',
        eventDescription: null,
        eventCategory: null,
        payoutAmount: 0,
        payoutTypeId: 1,
        payoutType: 'CPI',
        allowDuplicateEvents: false,
        maxTime: null,
        maxTimeMetric: null,
        enforceEventOrder: false,
        enforceMaxTimeCompletion: false,
        everflowEventId: 27932,
        appEventId: 845,
        userPayout: null,
      },
      {
        id: 312999,
        identifier: 'log_city_upgrade_5',
        eventName: 'Upgrade the Queen to level 5',
        eventDescription: 'Purchase one supreme worker',
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 0.39,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 28178,
        appEventId: 836,
        userPayout: null,
      },
      {
        id: 313000,
        identifier: 'log_city_upgrade_8',
        eventName: 'Upgrade the Queen to level 8',
        eventDescription: 'Purchase one supreme worker',
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 0.78,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 34092,
        appEventId: 3105,
        userPayout: null,
      },
      {
        id: 313001,
        identifier: 'log_city_upgrade_10',
        eventName: 'Upgrade the Queen to level 10',
        eventDescription: null,
        eventCategory: 'Level achieved - Easy',
        payoutAmount: 2.6,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 28865,
        appEventId: 844,
        userPayout: null,
      },
      {
        id: 313002,
        identifier: 'log_city_upgrade_13',
        eventName: 'Upgrade the Queen to level 13',
        eventDescription: '3-7 days',
        eventCategory: 'Level achieved - Medium',
        payoutAmount: 6.5,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 27935,
        appEventId: 841,
        userPayout: null,
      },
      {
        id: 313003,
        identifier: 'log_city_upgrade_16',
        eventName: 'Upgrade the Queen to level 16',
        eventDescription: '5-8 days',
        eventCategory: 'Level achieved - Medium',
        payoutAmount: 19.5,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 27936,
        appEventId: 840,
        userPayout: null,
      },
      {
        id: 313004,
        identifier: 'log_city_upgrade_18',
        eventName: 'Upgrade the Queen to level 18',
        eventDescription: '15-30 days',
        eventCategory: 'Level achieved - High',
        payoutAmount: 32.5,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 27937,
        appEventId: 839,
        userPayout: null,
      },
      {
        id: 313005,
        identifier: 'log_city_upgrade_25',
        eventName: 'Upgrade the Queen to level 25',
        eventDescription: '28 days +',
        eventCategory: 'Level achieved - High',
        payoutAmount: 130,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: true,
        enforceMaxTimeCompletion: true,
        everflowEventId: 27938,
        appEventId: 838,
        userPayout: null,
      },
      {
        id: 313006,
        identifier: 'plan_light_contract',
        eventName: 'Purchase 1 light contract',
        eventDescription: 'Purchase one light contract',
        eventCategory: 'Purchase',
        payoutAmount: 23.4,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: false,
        everflowEventId: 27934,
        appEventId: 842,
        userPayout: null,
      },
      {
        id: 313007,
        identifier: 'worker_ants_1',
        eventName: 'Purchase supreme worker 1',
        eventDescription: 'Purchase one supreme worker',
        eventCategory: 'Purchase',
        payoutAmount: 3.9,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: false,
        everflowEventId: 27933,
        appEventId: 843,
        userPayout: null,
      },
      {
        id: 313008,
        identifier: 'worker_ants_2',
        eventName: 'Purchase Supreme Worker II',
        eventDescription: null,
        eventCategory: 'Purchase',
        payoutAmount: 6.5,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: false,
        everflowEventId: 40858,
        appEventId: 4745,
        userPayout: null,
      },
      {
        id: 313009,
        identifier: 'worker_ants_3',
        eventName: 'Purchase Suprene Worker III',
        eventDescription: null,
        eventCategory: 'Purchase',
        payoutAmount: 13,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: false,
        everflowEventId: 40859,
        appEventId: 4746,
        userPayout: null,
      },
      {
        id: 313010,
        identifier: 'worker_ants_4',
        eventName: 'Purchase Supreme Worker IV',
        eventDescription: null,
        eventCategory: 'Purchase',
        payoutAmount: 32.5,
        payoutTypeId: 2,
        payoutType: 'CPA',
        allowDuplicateEvents: false,
        maxTime: 30,
        maxTimeMetric: 'days',
        enforceEventOrder: false,
        enforceMaxTimeCompletion: false,
        everflowEventId: 40860,
        appEventId: 4747,
        userPayout: null,
      },
    ],
    publisherBudgets: [
      {
        id: 47771,
        budgetType: {
          id: 3,
          name: 'Click Caps',
        },
        dailyBudget: null,
        weeklyBudget: null,
        monthlyBudget: null,
        globalBudget: null,
        isActive: true,
      },
      {
        id: 47772,
        budgetType: {
          id: 4,
          name: 'Conversion Caps',
        },
        dailyBudget: null,
        weeklyBudget: null,
        monthlyBudget: null,
        globalBudget: null,
        isActive: true,
      },
      {
        id: 47773,
        budgetType: {
          id: 5,
          name: 'Revenue Caps',
        },
        dailyBudget: null,
        weeklyBudget: null,
        monthlyBudget: null,
        globalBudget: null,
        isActive: true,
      },
    ],
    tracking: {
      id: 2186,
      attributionTool: 'Appsflyer',
      clickUrl: 'https://www.ltv-mob.com/KMHQ5J/2BWJKTN9/',
      impressionUrl: 'https://www.ltv-mob.com/i/KMHQ5J/2BWJKTN9/',
    },
    targeting: {
      os: 'Android',
      countries: [
        {
          id: 226,
          iso: 'US',
        },
      ],
      demographics: [],
      targetingType: 'incent',
      reward: {
        rewardDifficulty: 'Medium',
        incentRewardDescription:
          '1. Play and enjoy {game_name}. \n2. Complete the tasks listed to collect your points! \n3. Each task has a time limit! Complete the event on time to be able to collect the points! \n4. You must be a new player to get rewarded.\n\n- Upgrade the Queen to level 5 - Complete within 30 days\n- Upgrade the Queen to level 8 - Complete within 30 days\n- Upgrade the Queen to level 10 - Complete within 30 days\n- Upgrade the Queen to level 13 - Complete within 30 days\n- Upgrade the Queen to level 16 - Complete within 30 days\n- Upgrade the Queen to level 18 - Complete within 30 days\n- Upgrade the Queen to level 25 - Complete within 30 days\n- Purchase 1 light contract - Complete within 30 days\n- Purchase supreme worker 1 - Complete within 30 days\n- Purchase Supreme Worker II - Complete within 30 days\n- Purchase Suprene Worker III - Complete within 30 days\n- Purchase Supreme Worker IV - Complete within 30 days',
      },
    },
    creative: {
      creativeUrl: '.',
      creativePacks: [
        {
          creativePackName: 'The Ants: Underground Kingdom',
          languageName: 'English',
          languageCode: 'en',
          creatives: [
            {
              creativeName: 'The_Ants:_Underground_Kingdom_rewardedBanner_0x0',
              callToAction: '',
              text: '',
              byteSize: '',
              fileUrl:
                'https://d1qzgjkat5an4y.cloudfront.net/299/The_Ants:_Underground_Kingdom_rewardedBanner_0x0.webp',
              duration: '',
              creativeType: {
                name: 'Rewarded Banner',
                type: 'image',
                width: '1200',
                height: '627',
                creativeCategoryType: 'Rewarded Play',
              },
            },
          ],
        },
      ],
    },
  },
]

export default campaigns
